# Generated by Django 5.2.12 on 2026-04-07 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientRegister_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=3000)),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='csvdatasets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=3000)),
                ('IPAddress', models.CharField(max_length=3000)),
                ('App_Name', models.CharField(max_length=3000)),
                ('Device', models.CharField(max_length=3000)),
                ('OS', models.CharField(max_length=3000)),
                ('Channel', models.CharField(max_length=3000)),
                ('Click_time', models.CharField(max_length=3000)),
                ('Time_to_click', models.CharField(max_length=3000)),
                ('Session_duration', models.CharField(max_length=3000)),
                ('Mouse_movement', models.CharField(max_length=3000)),
                ('IP_frequency', models.CharField(max_length=3000)),
                ('Referrer_missing', models.CharField(max_length=3000)),
                ('Scroll_depth', models.CharField(max_length=3000)),
                ('Time_on_page', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='detection_accuracy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='detection_ratio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=300)),
                ('ratio', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='predict_ad_click_fraud_detection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fid', models.CharField(max_length=3000)),
                ('IPAddress', models.CharField(max_length=3000)),
                ('App_Name', models.CharField(max_length=3000)),
                ('Device', models.CharField(max_length=3000)),
                ('OS', models.CharField(max_length=3000)),
                ('Channel', models.CharField(max_length=3000)),
                ('Click_time', models.CharField(max_length=3000)),
                ('Time_to_click', models.CharField(max_length=3000)),
                ('Session_duration', models.CharField(max_length=3000)),
                ('Mouse_movement', models.CharField(max_length=3000)),
                ('IP_frequency', models.CharField(max_length=3000)),
                ('Referrer_missing', models.CharField(max_length=3000)),
                ('Scroll_depth', models.CharField(max_length=3000)),
                ('Time_on_page', models.CharField(max_length=3000)),
                ('Prediction', models.CharField(max_length=3000)),
            ],
        ),
    ]
